### ISSUE TITLE
Stable version composer.json bug

### ISSUE THREAD

**Issue by splokhikh** [merorafael/yii2-monolog#1]
Stable version 0.1.0 composer.json contains bad psr-4 autoload mapping:
`
"psr-4": { "Mero\\Monolog\\": "src/Monolog" }
`

Should be:
`
"psr-4": { "Mero\\Monolog\\": "src/Mero/Monolog" }
`

**Comment by merorafael** [comment]
Fixed in version 0.1.1. Thank's for reporting.
